import { Router } from "express";
import { protect } from "../middleware/auth.js";
import { requireAdmin } from "../middleware/admin.js";
import { getAdminOverview, getAdminProducts, createAdminProduct, updateAdminProduct, adjustAdminStock, archiveAdminProduct, restoreAdminProduct, getStockAdjustments, getAdminSettings, updateAdminSettings } from "../controllers/adminController.js";
import { previewProductImport, importProducts } from "../controllers/adminImportController.js";
import { getAdminCategories, createCategory, updateCategory, deleteCategory, getAdminBadges, createBadge, updateBadge, deleteBadge } from "../controllers/adminTaxonomyController.js";

const router = Router();
router.use(protect, requireAdmin);
router.get("/overview", getAdminOverview);
router.get("/categories", getAdminCategories);
router.post("/categories", createCategory);
router.patch("/categories/:key", updateCategory);
router.delete("/categories/:key", deleteCategory);
router.get("/badges", getAdminBadges);
router.post("/badges", createBadge);
router.patch("/badges/:id", updateBadge);
router.delete("/badges/:id", deleteBadge);
router.get("/products", getAdminProducts);
router.post("/products", createAdminProduct);
router.post("/products/import/preview", previewProductImport);
router.post("/products/import", importProducts);
router.patch("/products/:id", updateAdminProduct);
router.patch("/products/:id/stock", adjustAdminStock);
router.delete("/products/:id", archiveAdminProduct);
router.patch("/products/:id/restore", restoreAdminProduct);
router.get("/stock-adjustments", getStockAdjustments);
router.get("/settings", getAdminSettings);
router.patch("/settings", updateAdminSettings);
export default router;
